apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.defgault.src
  project: default
  source:
    path: .
    repoURL: 'https://github.com/dellabeneta/test-k8s-green-blue.git'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      automated:
        selfHeal: true
        prune: true