apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.src
  project: default
  source:
    path: k8s
    repoURL: 'https://github.com/dellabeneta/test-k8s-green-blue'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true